version: '3'
services:
  node:
    restart: always
    container_name: '${APP_NAME}-node'
    build: 
      context: ./apis/api-nodejs/build
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - menhir_finder

  client:
    restart: always
    container_name: '${APP_NAME}-client'
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - ${APP_CLIENT_PORT}:80
    volumes:
      - ./client/dist/browser:/var/www/html/
    networks:
      - menhir_finder
    depends_on:
      - php
      - node

  php:
    build:
      context: ./apis/api-php/build
      dockerfile: Dockerfile
    container_name: '${APP_NAME}-server'
    restart: always
    ports:
      - '${APP_PORT}:80'
    working_dir: /var/www/html
    environment:
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASS}'
      MYSQL_DATABASE: '${MYSQL_DB}'
      TZ: 'Europe/Paris'
    volumes:
      - ./apis/api-php/app:/var/www/html
      - ./apis/api-php/images:/data
      - ./apis/api-php/web/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./apis/api-php/web/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
    depends_on:
      - db
    networks:
      - menhir_finder

  db:
    image: mariadb:latest
    container_name: '${APP_NAME}-db'
    restart: always
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASS}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASS}'
      MYSQL_DATABASE: '${MYSQL_DB}'
    volumes:
      - ./db/data/:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
    networks:
      - menhir_finder
networks:
  menhir_finder:
